---
title: "Expression analysis in the HN cohort"
author: "Maria Secrier"
date: "11/10/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "plots/")
```

## Libraries

```{r libs, echo=FALSE}
library(ggplot2)
library(reshape)
library(ggpubr)
library(corrplot)
library(nnet)
library(mlogit)
library(MASS)
library(glmnet)
library(cowplot)
```

## Reading data

```{r readdata, echo=FALSE}
## Clinical and expression data:
load("dat.annot.plusimm.2021.RData")
my_comparisons <- list(c("Absent","MacrophageRich"),
                       c("MacrophageRich","DCrich"),
                       c("DCrich","PCrich"),
                       c("PCrich","Cytotoxic"))

load("bulkExpMatrix.162.RData")
dat.hn <- data.frame(t(bulkExpMatrix))
dat.hn$Sample <- sapply(rownames(dat.hn),
                        function(x) paste(strsplit(x,"\\.")[[1]],collapse="-"))

dat.merged <- merge(dat.hn, 
                    dat.annot.plusimm,
                    all.x=FALSE, all.y=FALSE,
                    by.x="Sample", by.y="Sample")
dat.hn <- dat.merged
dat.hn$I <- sapply(dat.hn$ImmunityGroup, 
                   function(x) ifelse (x %in% c("Absent","MacrophageRich"),"Low","High"))
dat.hn$ImmunityGroup <- dat.hn$I

## Genes of interest:
rtks <- read.table("../../../data/RTKgeneList.txt",
                   header=TRUE, sep="\t",
                   stringsAsFactors = FALSE)

```


## EGFR/MAPK/ERK/PI3K/mTOR phenotypes

Select genes with available expression from NanoString:
```{r rtk, echo=FALSE}
selectedRTK <- colnames(dat.hn)[which(colnames(dat.hn) %in% rtks$Gene)]
length(selectedRTK)
```

Compare the expression between the exhaustion groups:
```{r rtkExpression.compared, fig.width=8, fig.height=12}

df.rtk <- melt(dat.hn[,c("Sample","ImmunityGroup",selectedRTK)])
df.rtk.keep <- df.rtk[which(!is.na(df.rtk$ImmunityGroup)),]

immunityColor <- data.frame(Colour=c("Low"="#4A6FA5",
                                  "High"="#993955"))

df.rtk.keep$ImmunityGroup <- factor(df.rtk.keep$ImmunityGroup, 
                       levels = c("Low",
                                  "High"))

my_comparisons <- list(c("Low","High"))

# dodge <- position_dodge(width = 0.4)
# ggplot(df.rtk.keep, aes(x=ImmunityGroup, y=value))+ #, color=immunityColor$Colour))+
#   geom_violin(position = dodge)+
#   geom_boxplot(width=.1, outlier.colour=NA, position = dodge) +
#   facet_wrap(~variable,nrow=4)+
#   stat_compare_means(comparisons=my_comparisons,label="p.signif")+
#   stat_compare_means(label.y=25)

pdf("plots2021.extra/rtk.LowHigh/rtks.comparedBetweenImmGr.pdf",w=10,h=15)
ggviolin(df.rtk.keep, 
          x = "ImmunityGroup", 
          y = "value",
          palette = c("#4A6FA5", "#993955"),
          fill = "ImmunityGroup",
         add="boxplot",
         add.params = list(fill = "white"))+
  xlab("Immunity group")+
  ylab("Expression")+
  facet_wrap(~variable,scales = "free")+
  theme(axis.text.x=element_blank())+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
  stat_compare_means(label.y = 0, label.x= 1.5)
dev.off()

pdf("plots2021.extra/rtk.LowHigh/rtks.comparedBetweenImmGr.selected.pdf",w=10,h=12)
ggviolin(df.rtk.keep[which(df.rtk.keep$variable %in% selectedRTK),], 
          x = "ImmunityGroup", 
          y = "value",
          palette = c("#4A6FA5", "#993955"),
          fill = "ImmunityGroup",
         add="boxplot",
         add.params = list(fill = "white"))+
  xlab("Immunity group")+
  ylab("Expression")+
  facet_wrap(~variable,scales = "free")+
  theme(axis.text.x=element_blank())+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
  stat_compare_means(label.y = 0, label.x= 0.5)
dev.off()

```

Correlation with productive clonality?
```{r correlation_rtkVsClonality, fig.width=8, fig.height=12}

df.rtk <- melt(dat.hn[which(!is.na(dat.hn$Productive.Clonality)),c("Sample",selectedRTK)])
df.clon <- dat.hn[which(!is.na(dat.hn$Productive.Clonality)),c("Sample","Productive.Clonality")]
df.merged <- merge(df.rtk,df.clon,
                   by.x="Sample", by.y="Sample",
                   all.x=FALSE,all.y=FALSE)

pdf("plots2021.extra//rtk.LowHigh/corr.withProdClon.pdf",w=15,h=5)
ggplot(df.merged, aes(value, Productive.Clonality))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~variable,nrow=3, scales="free")
dev.off()

pdf("plots2021.extra//rtk.LowHigh/corr.withProdClon.ggscatter.pdf",w=15,h=10)
ggscatter(df.merged, x="value", y="Productive.Clonality",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE,color="darkgrey")+
  facet_wrap(~variable,nrow=5, scales="free")+
  ylab("Productive clonality")+
  xlab("Gene expression")
dev.off()

df.rich <- dat.hn[which(!is.na(dat.hn$observed_richness)),c("Sample","observed_richness")]
df.merged <- merge(df.rtk,df.rich,
                   by.x="Sample", by.y="Sample",
                   all.x=FALSE,all.y=FALSE)

pdf("plots2021.extra//rtk.LowHigh/corr.withObsRich.ggscatter.pdf",w=15,h=10)
ggscatter(df.merged, x="value", y="observed_richness",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE,color="darkgrey")+
  facet_wrap(~variable,nrow=5, scales="free")+
  ylab("Observed richness")+
  xlab("Gene expression")
dev.off()

```

Predict exhaustion groups based on RTK expression using multinomial logistic regression:
```{r rtkPreditionModel}

dat.selected <- dat.hn[which(!is.na(dat.hn$ImmunityGroup)),c(selectedRTK,"ImmunityGroup")]
dat.selected$ImmunityGroup <- factor(dat.selected$ImmunityGroup)
dat.selected.keep <- dat.selected

### Select train and test sets, dividing into 2/3 for train, 1/3 for test:
set.seed(19875) 
randTrainingSet <- sample(1:162, 108, replace=F)
dat.train <- dat.selected.keep[randTrainingSet,]
dat.test <- dat.selected.keep[setdiff(1:143,randTrainingSet),]
dat.train.x <- as.matrix(dat.train[,1:(ncol(dat.train)-1)])
dat.train.y <- dat.train$ImmunityGroup
dat.test.x <- as.matrix(dat.test[,1:(ncol(dat.test)-1)])
dat.test.y <- dat.test$ImmunityGroup

# Fit multinomial logistic regression model:
glm.fitFull=multinom(ImmunityGroup~0+., data=dat.train)
summary(glm.fitFull)
z <- summary(glm.fitFull)$coefficients/summary(glm.fitFull)$standard.error
# 2-tailed z test
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
glm.fit.null=multinom(ImmunityGroup~1, data=dat.train)
anova(glm.fitFull, glm.fit.null)

#############
# define model grid for best subset regression
# defines which predictors are on/off; all combinations presented
# from https://stackoverflow.com/questions/41061729/how-to-get-the-best-subset-for-a-multinomial-regression-in-r
model.grid <- function(n){
     n.list <- rep(list(0:1), n)
     expand.grid(n.list)
}
model.grid(length(selectedRTK))

# function for best subset regression
# ranks predictor combos using 5 selection criteria

 best.subset <- function(y, x.vars, data){
 # y       character string and name of dependent variable
 # xvars   character vector with names of predictors
 # data    training data with y and xvar observations

 require(dplyr)
 require(purrr)
 require(magrittr)
 require(forecast)

 length(x.vars) %>%
      model.grid %>%
      apply(1, function(x) which(x > 0, arr.ind = TRUE)) %>%
      map(function(x) x.vars[x]) %>%
      .[2:dim(model.grid(length(x.vars)))[1]] %>%
      map(function(x) fit=multinom(paste0(y, " ~ 0+", paste(x, collapse = "+")), data = data)) %>%
      map("AIC") %>%
      do.call(rbind, .) %>%
      cbind(model.grid(length(x.vars))[-1, ], .) 
}

library(fpp2)

## Further reduce selected RTKs based on differences between groups: 
#selectedRTK <- c("EGFR","HRAS","IGF1R","MAP2K1","MAP2K2","MAP2K4",
#                 "MAPK1","PIK3CD","PIK3CG")
# selectedRTK <- c("EGFR","HRAS","IGF1R",
#                 "MAPK1","PIK3CD","PIK3CG")
  selectedRTK <- c("EGFR", "IGF1R", "KRAS", "MAPK1", "MET", "PIK3CA", "PIK3CD", "PIK3CG", "PIK3R1", "PIK3R2", "PIK3R5", "PTEN")

# test the function
compareall <- best.subset("ImmunityGroup", selectedRTK, dat.train) 
colnames(compareall) <- c(selectedRTK,"AIC")
coptimum <- compareall[which(compareall$AIC == min(compareall$AIC)),]
#      ERBB2 PIK3CD PIK3CG PIK3R5      AIC
#8     1      1      1      0 41.57629
#      EGFR IGF1R KRAS MAPK1 MET PIK3CA PIK3CD PIK3CG PIK3R1 PIK3R2 PIK3R5 PTEN      AIC
# 1231    0     1    1     1   0      0      1      1      0      0      1    0 76.17514

# Reduced, optimal model with minimum AIC:
rtksToKeep <- names(coptimum[which(coptimum==1)])
glm.fit=multinom(paste0("ImmunityGroup~ 0+", paste(rtksToKeep, collapse = "+")), data = dat.train)
summary(glm.fit)
z <- summary(glm.fit)$coefficients/summary(glm.fit)$standard.error
# 2-tailed z test
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
anova(glm.fit,glm.fit.null)

save(glm.fit, file="glm.fit.optimised.CTME.highLow.RData")
# p=2.220446e-16  ---3.907985e-14 

## Predictions:
predicted=predict(glm.fit,dat.test,type="probs")
bpp=cbind(dat.test, predicted)
bpp$Low <- bpp$predicted
bpp$High <- 1-bpp$Low
bpp2 <- melt(bpp[,c("ImmunityGroup",rtksToKeep,
                    "Low","High")],
             id.vars = c("ImmunityGroup",rtksToKeep))
colnames(bpp2)[c(ncol(bpp2)-1,ncol(bpp2))] <- c("Prediction","Probability")
bpp.truth <- unique(bpp2[,c("ImmunityGroup",rtksToKeep)])
bpp.truth$ImmG <- sapply(bpp.truth$ImmunityGroup,
                        function(x) ifelse(x=="Low",0,1))
bpp.truth$ImmunityGroup <- factor(bpp.truth$ImmunityGroup,levels=c("Low","High"))
bpp2$ImmunityGroup <- factor(bpp2$ImmunityGroup,levels=c("Low","High"))

p.pred <- list()
p.truth <- list()
i <- 0 
for (r in rtksToKeep) {
  i <- i+1
  p.pred.current <- ggplot(bpp2, aes_string(x = r, y = "Probability", colour = "Prediction")) +
         geom_line() + facet_grid(Prediction ~ ., scales="free")+
    ylim(c(0,1))+
    ylab("Probability")
  p.truth.current <- ggplot(bpp.truth,aes_string(x=r,y="ImmunityGroup"))+
    geom_boxplot(width=5)+
    geom_point(size=3, alpha=0.5)+
    theme(plot.margin=unit(c(t=0,r=3.3,b=0,l=0),"cm"))+
    ylab("Immunity")
  p.pred[[i]] <- p.pred.current
  p.truth[[i]] <- p.truth.current
  
  pdf(paste0("plots2021.extra/rtk.LowHigh/",r,"predictedImmunity.4.pdf"))
  print(plot_grid(p.pred.current,p.truth.current,nrow=2,align="hv", axis="l",
            rel_heights = c(1,0.2)))
  dev.off()
}
  
pdf(paste0("plots2021.extra/rtk.LowHigh/rtksALL.predictedExhaustion.4.pdf"),w=15,h=6)
plot_grid(p.pred[[1]],p.pred[[2]],p.pred[[3]],p.pred[[4]],p.pred[[5]],p.pred[[6]],
          p.truth[[1]],p.truth[[2]],p.truth[[3]],p.truth[[4]],p.truth[[5]],p.truth[[6]],
                nrow=2,align="hv", axis="l",
            rel_heights = c(1,0.3))+ theme(legend.position = "none")
dev.off()

### Now fitting regression:

p.pred <- list()
p.truth <- list()
i <- 0 
for (r in rtksToKeep) {
  i <- i+1
    p.pred.current <- ggplot(bpp2, aes_string(x = r, y = "Probability", colour = "Prediction")) +
         geom_point(size=3) + 
    geom_smooth(method="loess",se=TRUE)+
    scale_color_manual(values=c("#336699","#993955"))+
    facet_grid(Prediction ~ ., scales="free")+
    ylim(c(0,1))+
    ylab("Probability")+
    theme(legend.position = "none") # no legend
  p.truth.current <- ggplot(bpp.truth,aes_string(x=r,y="ImmunityGroup"))+
    geom_boxplot(width=5)+
    geom_point(size=3, alpha=0.5)+
    theme(plot.margin=unit(c(t=0,r=0.8,b=0,l=0),"cm"))+
    ylab("Immunity")
  p.pred[[i]] <- p.pred.current
  p.truth[[i]] <- p.truth.current
}

pdf(paste0("plots2021.extra/rtk.LowHigh/rtksALL.predictedExhaustion.fittedRegression.pdf"),w=12,h=5)
plot_grid(p.pred[[1]],p.pred[[2]],p.pred[[3]],p.pred[[4]],p.pred[[5]],p.pred[[6]],
          p.truth[[1]],p.truth[[2]],p.truth[[3]],p.truth[[4]],p.truth[[5]],p.truth[[6]],
                nrow=2,align="hv", axis="l",
            rel_heights = c(1,0.3))+ theme(legend.position = "none")
dev.off()

pdf(paste0("plots2021.extra/rtk.LowHigh/rtksALL.predictedExhaustion.fittedRegression.selected.pdf"),w=12,h=5)
plot_grid(p.pred[[4]],p.pred[[5]],p.pred[[6]],
          p.truth[[4]],p.truth[[5]],p.truth[[6]],
                nrow=2,align="hv", axis="l",
            rel_heights = c(1,0.3))+ theme(legend.position = "none")
dev.off()
  

### Calculate FP and FN rates:

phen.predicted <- apply(bpp[,c("Low","High")], 1, function(x)
  colnames(bpp[,c("Low","High")])[which(x==max(x))])
phen.truth <- dat.test$ImmunityGroup
length(which(phen.predicted==phen.truth))
length(which(phen.predicted!=phen.truth))
39/(39+9)

# considering all RTKs:
#???

# considering only significant ones:
#???

# considering only significant ones ** and above:
#41/48
#7/48



## Validation in TCGA:
load("TCGA.dat.tcga.expr.RData")
load("dat.annot.TCGA.log2.RData")
dat.annot.tcga <- dat.annot
dat.annot.tcga$ImmunityGroup <- sapply(dat.annot.tcga$Group,
                                  function(x) ifelse(x %in% c(1,2),"Low","High"))
dat.annot.tcga$Sample <- rownames(dat.annot.tcga)

dat.tcga.expr$Sample <- rownames(dat.tcga.expr)

dat.tcga <- merge(dat.tcga.expr[,c("Sample",selectedRTK)],
                  dat.annot.tcga[,c("Sample","ImmunityGroup")],
                  by.x="Sample",by.y="Sample",
                  all.x=FALSE, all.y=FALSE)

predicted.tcga=predict(glm.fit,dat.tcga[,-1],type="probs")
bpp.tcga=cbind(dat.tcga[,-1], predicted.tcga)
bpp.tcga$Low <- bpp.tcga$predicted.tcga
bpp.tcga$High <- 1-bpp.tcga$Low

phen.predicted.tcga <- apply(bpp.tcga[,c("Low","High")], 1, function(x)
  colnames(bpp.tcga[,c("Low","High")])[which(x==max(x))])
phen.truth.tcga <- dat.tcga$ImmunityGroup
length(which(phen.predicted.tcga==phen.truth.tcga))
length(which(phen.predicted.tcga!=phen.truth.tcga))

437/520

simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}

labels <- sapply(phen.truth.tcga,
                 function(x) ifelse(x=="High",1,0))
scores <- sapply(phen.predicted.tcga,
                 function(x) ifelse(x=="High",1,0))
glm_simple_roc <- simple_roc(labels,scores)

library(pROC)
roc_obj <- roc(labels,scores)
auc(roc_obj)

pdf("plots2020/TCGA.valid.RTK.ROC.pdf")
ggplot(glm_simple_roc,aes(FPR,TPR))+
  geom_line()
dev.off()

(sum(labels)-sum(scores))/sum(labels)

summary(predicted)

```

